# Generated by Django 5.1.1 on 2024-10-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripbudget',
            name='trip',
        ),
    ]
