# Generated by Django 5.1.1 on 2024-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='name',
            field=models.CharField(max_length=255, verbose_name=models.Model),
        ),
        migrations.AlterField(
            model_name='neededlist',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='trip.itemlist'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='item_list',
            field=models.ManyToManyField(blank=True, null=True, to='trip.neededlist'),
        ),
    ]
