# Generated by Django 5.1.1 on 2024-10-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_alter_itemlist_name_alter_neededlist_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='neededlist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
