# Generated by Django 5.1.1 on 2024-10-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_itemlist_name_alter_neededlist_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemList',
            new_name='Item',
        ),
    ]
