# Generated by Django 5.1.1 on 2024-10-09 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_neededlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='item_list',
        ),
        migrations.AddField(
            model_name='trip',
            name='item_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.neededlist'),
        ),
    ]
